mdl.lo: /Users/dimus/code/levenshtein_playground/php/mdl.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/Users/dimus/code/levenshtein_playground/php $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/dimus/code/levenshtein_playground/php/mdl.c -o mdl.lo 
$(phplibdir)/mdl.la: ./mdl.la
	$(LIBTOOL) --mode=install cp ./mdl.la $(phplibdir)

./mdl.la: $(shared_objects_mdl) $(MDL_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_mdl) $(MDL_SHARED_LIBADD)

